.TH DPKG-RECONFIGURE 8
.SH NAME
dpkg-reconfigure \- reconfigure an already installed package
.SH SYNOPSIS
.B dpkg-reconfigure [--frontend=\fItype\fP] [--priority=\fIvalue\fP] \fIpackage\fP [\fIpackage\fP ..]
.SH DESCRIPTION
.BR dpkg-reconfigure
reconfigures packages after they have already been installed. Pass it the
names of a package or packages to reconfigure.
.SH OPTIONS
.TP
.I "\fB\-f\fPtype\fR,\fP \fB\-\-frontend=\fPtype"
Select the frontend to use. The default frontend can be permanently changed
by: 

 dpkg-reconfigure debconf  

Currently avaialble frontends are dialog, text, and web.
.TP
.I "\fB\-p\fPvalue\fR,\fP \fB\-\-priority=\fPvalue"
Set the lowest priority of questions you are interested in. Valid priorities
are currently low, medium, high, and critical. The default priority can be
permanently changed by:

 dpkg-reconfigure --priority=medium debconf

Any questions with a priority below the selected priority will be ignored and
their default answers will be used.
.SH AUTHOR
Joey Hess <joey@kitenet.net>
