.TH DPKG-RECONFIGURE 1
.SH NAME
dpkg-reconfigure \- reconfigure an already installed package
.SH SYNOPSIS
.B dpkg-reconfigure [--frontend=type] [--priority=value] package [package ..]
.SH DESCRIPTION
.BR dpkg-reconfigure
reconfigures packages after they have already been installed. Pass it the
names of a package or packages to reconfigure.
.SH OPTIONS
.TP
.I "\-ftype, \-\-frontend=type"
Select the frontend to use. Default is to use the dialog based frontend.
Currently avaialble frontends are dialog, line, and web.
.TP
.I "\-pvalue, \-\-priority=value"
Set the lowest priority of questions you are interested in. Valid priorities
are currently low, medium, high, and critical. Default is medium. Any
questions with a priority below the selected priority will be ignored and
their default answers will be used.
.SH AUTHOR
Joey Hess <joey@kitenet.net>
