.TH DPKG-PRECONFIG 1
.SH NAME
dpkg-preconfig \- let packages ask questions prior to their installation
.SH SYNOPSIS
.B dpkg-preconfig [--frontend=type] [--priority=value] file.deb [file.deb ..]
.SH DESCRIPTION
.BR dpkg-preconfig
lets packages ask questions before they are installed. It operates on a set
of debian packages, and all packages that use debconf will have thier config
script run so they can examine the system and ask questions.
.SH OPTIONS
.TP
.I "\-ftype, \-\-frontend=type"
Select the frontend to use. Default is to use the dialog based frontend.
Currently avaialble frontends are dialog, line, and web.
.TP
.I "\-pvalue, \-\-priority=value"
Set the lowest priority of questions you are interested in. Valid priorities
are currently low, medium, high, and critical. Default is medium. Any
questions with a priority below the selected priority will be ignored and
their default answers will be used.
.TP
.I \-\-apt
Run in apt mode. It will expect to read a set of package filenames from stdin,
rather than getting them as parameters. Typically this is used to make apt
run dpkg-preconfig on all packages before they are installed. To do this,
add something like this to /etc/apt/apt.conf:
 // Pre-configure all packages before they are installed.
 DPkg::Pre-Install-Pkgs {"dpkg-preconfig --apt --priority=low";};
.SH AUTHOR
Joey Hess <joey@kitenet.net>
