#!/usr/bin/perl -w

=head1 NAME

dpkg-loadtemplate - load template file into debconf database

=cut

use strict;
use Debian::DebConf::Config qw(dbdir);
use Debian::DebConf::ConfigDb qw(loaddb loadtemplatefile savedb);

=head1 SYNOPSIS

 dpkg-loadtemplate owner file [file ..]

=head1 DESCRIPTION

Loads one of more template files into the debconf database. The first
parameter specifies the owner of the templates (typically, the owner is the
name of a debian package). The remaining parameters are template files to
load.

=head1 WARNING

This program should never be used from a maintainer script of a package
that uses debconf! It may however, be useful in debugging, or to seed the
debconf database.

=cut

my $owner=shift;
loaddb(dbdir());
loadtemplatefile($_, $owner) foreach @ARGV;
savedb(dbdir());

=head1 AUTHOR

Joey Hess <joey@kitenet.net>

=cut

