.TH DEBCONF 8
.SH NAME
debconf \- Debian package configuration system
.SH DESCRIPTION
Debconf is a configuration system for Debian packages. There is no
command named "debconf".
.SH SEE ALSO
.BR debconf.conf (5),
.BR dpkg-preconfigure (8),
.BR dpkg-reconfigure (8),
.BR /usr/share/doc/debconf-doc/usersguide.txt.gz
.SH AUTHOR
Joey Hess <joey@kitenet.net>
