#!/usr/bin/perl -w

=head1 NAME

debconf-loadtemplate - load template file into debconf database

=cut

use strict;
use Debian::Debconf::Config qw(dbdir);
use Debian::Debconf::Template;
use Debian::Debconf::ConfigDb qw(loaddb registertemplates savedb);

=head1 SYNOPSIS

 debconf-loadtemplate owner file [file ..]

=head1 DESCRIPTION

Loads one of more template files into the debconf database. The first
parameter specifies the owner of the templates (typically, the owner is the
name of a debian package). The remaining parameters are template files to
load.

=head1 WARNING

This program should never be used from a maintainer script of a package
that uses debconf! It may however, be useful in debugging, or to seed the
debconf database.

=head1 SEE ALSO

L<debconf-communicate(8)|debconf-communicate>

=cut

my $owner=shift;
registertemplates($owner, Debian::Debconf::Template->load($_)) foreach @ARGV;
savedb(dbdir());

=head1 AUTHOR

Joey Hess <joey@kitenet.net>

=cut

