=head1 NOM

debconf-get-selections

=head1 SYNOPSIS

debconf-get-selections


Affiche la base de données actuelle de debconf dans un format compréhensible par
debconf-set-selections.

=cut

=head1 AUTEUR

Petter Reinholdtsen <pere@hungry.com>

=head1 TRADUCTION

Julien Louis <leonptitlouis@ifrance.com>

=cut

