=head1 NOM

debconf-loadtemplate - charge un questionnaire dans la base de données de
debconf

=head1 SYNOPSIS

 debconf-loadtemplate propriétaire fichier [fichier ..]

=head1 DESCRIPTION

Ce programme charge un ou plusieurs questionnaires dans la base de données de
debconf. Le premier paramètre spécifie le propriétaire du questionnaire
(généralement, le propriétaire est le nom du paquet). Les paramètres restants
sont les questionnaires à charger.

=head1 ATTENTION

Ce programme ne devrait jamais être utilisé par les scripts de maintenance d'un
paquet qui utilise debconfE<nbsp>! Il devrait, cependant, être utile pour le
debogage ou pour remplir la base de données de debconf.

=head1 VOIR AUSSI

L<debconf-communicate(1)>

=head1 AUTEUR

Joey Hess <joeyh@debian.org>

=head1 TRADUCTION

Julien Louis <leonptitlouis@ifrance.com>

