=head1 NOM

debconf-communicate - communiquer avec debconf

=head1 SYNOPSIS

 echo commandes | debconf-communicate [options] [paquet]

=head1 DESCRIPTION

B<debconf-communicate> permet de communiquer à la volée avec debconf depuis la
ligne de commande. Le paquet en argument est le nom du paquet que vous voulez
faire communiquer avec debconf, il peut être omis si vous êtes paresseux. Ce
programme lit depuis l'entrée standard des commandes utilisées par le protocole
de debconf. Pour la documentation sur les commandes disponibles ainsi que leur
usage, voyez la spécification debconf.

Les commandes sont exécutées dans l'ordre. Le code de retour de chaque commande
est affiché sur la sortie standard.

La valeur de retour de ce programme est le chiffre de retour de la dernière
commande exécutée.

=head1 EXEMPLE

 echo get debconf/frontend | debconf-communicate

Imprime l'importance de la question de l'interface/debconf.

=head1 ATTENTION

Ce programme ne devrait pas être utilisé par les scripts de maintenance d'un
paquet qui utilise debconfE<nbsp>! Il peut, cependant, être utile pour le
débogage.

=head1 VOIR AUSSI

L<debconf-loadtemplate(1)>

=head1 AUTEUR

Joey Hess <joeyh@debian.org>

=head1 TRADUCTION

Julien Louis <leonptitlouis@ifrance.com>
