=head1 NOME

debconf-mergetemplate - une múltiplos arquivos de modelos debconf

=head1 RESUMO

 debconf-mergetemplate arquivo [arquivo ..]

=head1 DESCRIÇÃO

Este programa é útil se você possui múltiplos arquivos de modelos debconf
os quais você quer unir em um único grande arquivo. Todos os arquivos
especificados serão lidos, unidos, e o resultado será exibido na saída
padrão.

Isto pode ser especialmente útil se você está lidando com arquivos de
modelos traduzidos. Neste caso, você poderá ter seu arquivo de modelo
principal, mais diversos outros arquivos fornecidos pelos tradutores.
Estes arquivos terão campos traduzidos, e talvez os tradutores deixem as
versões em inglês que eles traduziram, para sua própria referência.

Portanto, você quer unir todos os arquivos de modelos traduzidos com seu
arquivo de modelo principal. Quaisquer campos que sejam únicos para os
arquivos traduzidos precisam ser adicionados nos modelos corretos, mas
quaisquer campos que eles possuam em comum deverão ser supercedidos pelos
campos no arquivo principal (o qual deve estar mais atualizado).

Este programa gerencia este caso apropriadamente, somente liste cada um
dos arquivos de modelos traduzidos, e então seu arquivo de modelos
principal por último.

=head1 VEJA TAMBÉM

L<debconf-getlang(1)>

=head1 AUTOR

Joey Hess <joey@kitenet.net>
