=head1 NOM

debconf-show - interroge la base de données de debconf

=head1 SYNOPSIS

 debconf-show nomdupaquet [...] [--db=nomdb]
 debconf-show --listowners [--db=nomdb]
 debconf-show --listsdbs

=head1 DESCRIPTION


B<debconf-show> vous permet d'interroger la base de données de debconf de
différentes manières.


L'utilisation la plus courante est « debconf-show nomdupaquet », qui affiche
tous les items possédés par un paquet donné de la base de données de
debconf, ainsi que leurs valeurs. Les questions ayant déjà été posées sont
précédées d'un « * ».


Cela peut être utile pour aider au débogage et particulièrement pratique
dans les rapports de bogues impliquant un paquet qui utilise debconf.

=head1 OPTIONS

=over 4

=item B<--db=>I<dbname>


Spécifie la base de données à interroger. Par défaut, debconf-show interroge
la base de données principale.

=item B<--listowners>


Liste tous les propriétaires des questions de la base de données. En
général, un propriétaire équivaut au nom d'un paquet debian.

=item B<--listdbs>

Liste toutes les bases de données disponibles.

=back

=head1 AUTEUR

Joey Hess <joeyh@debian.org> et Sylvain Ferriol

=head1 TRADUCTION

Julien Louis <leonptitlouis@ifrance.com>
