=head1 NOME

dpkg-preconfigure - permite pacotes façam suas perguntas antes de sua instalação

=head1 RESUMO

 dpkg-preconfigure [opções] pacote.deb

 dpkg-preconfigure --apt

=head1 DESCRIÇÃO

B<dpkg-preconfigure> permite que pacotes façam suas perguntas antes que os
mesmos sejam instalados. Opera em um conjunto de pacotes debian, e todos
os pacotes que usam debconf terão seus script de configuração assim os
mesmos podem examinar o sistema e fazer perguntas.

=head1 OPÇÕES

=over 4

=item B<-f>I<tipo>, B<--frontend=>I<tipo>

Selecione o frontend a usar.

=item B<-p>I<valor>, B<--priority=>I<valor>

Define a prioridade mais baixa de questões nas quais você está
interessado. Quaisquer questões com uma prioridade menor do que a
prioridade selecionada será ignorda e suas respostas padrão serão usadas.

=item B<--apt>

Executa no modo apt. Esperará ler um conjunto de nomes de arquivos de
pacotes a partir d entrada padrão (stdin) ao invés de obtê-los como
parâmetros. Tipicamente isto é usado para fazer o apt executar
dpkg-preconfigure em todos os pacotes antes que sejam instalados. Para
fazer isso, adicione algo como isso ao /etc/apt/apt.conf :

 // Préconfigure todos os pacotes antes
 // que eles sejam instalados.
 DPkg::Pre-Install-Pkgs {
 	"dpkg-preconfigure --apt --priority=low";
 };

=item B<-h>, B<--help>

Exibe a ajuda sobre o uso.

=back

=head1 VEJA TAMBÉM

L<debconf(8)>

=head1 AUTOR

Joey Hess <joeyh@debian.org>
