#!/bin/sh -e
# Demo config module. This is more a regression/stress test than anything.

# Note this stanza is only here to make this script work in an uninstalled
# debconf source tree, and is not needed in production code.
PATH=$PATH:Client                                                               
if [ -e Client/confmodule ]; then                                               
	. Client/confmodule                                                     
else                                                                            
	. /usr/share/debconf/confmodule                                         
fi 

db_version 2.0
db_capb
db_title Demo
db_input critical demo/string || true
db_input low demo/password || true
db_go || true
db_get demo/select
echo single item select color is: $RET
db_subst demo/select colors red, Yellow, green
db_beginblock
db_subst demo/select colors maroon
db_input low demo/select || true
db_input low demo/select || true
db_input low demo/multiselect || true
db_input low demo/boolean || true
db_input low demo/text || true
db_endblock
db_go || true
db_get demo/select
echo $RET
db_get demo/boolean
echo $RET
db_get demo/multiselect
echo $RET
db_input low demo/note || true
db_go

