#!/bin/sh -e

# Source the debconf library only because it ensures our config script is
# run.
. /usr/share/debconf/confmodule.sh

touch /etc/apt/apt.conf
echo '// Pre-configure all packages before they are installed.' >> /etc/apt/apt.conf
echo 'DPkg::Pre-Install-Pkgs {"dpkg-preconfig --apt";};' >> /etc/apt/apt.conf

# Make sure the directory has safe permissions.
chmod 700 /var/lib/debconf

#DEBHELPER#
