#!/bin/sh -e
if [ "$1" = "purge" ]; then
	rm -f /var/lib/debconf/debconf.db
fi
if [ -e /etc/apt/apt.conf ]; then
	cp /etc/apt/apt.conf /etc/apt/apt.conf.old
	(grep -iv "// Pre-configure all packages" /etc/apt/apt.conf.old | \
		grep -iv dpkg-preconfig > /etc/apt/apt.conf) || true
	rm -f /etc/apt/apt.conf.old
fi
#DEBHELPER#
