#!/bin/sh -e
#DEBHELPER#

# Hack up debconf database to use new object names. This goes away when we
# get a real database.
VARDIR=/var/lib/debconf
if [ "$1" = upgrade ] && dpkg --compare-versions "$2" lt 0.4.00; then
	cp $VARDIR/debconf.db $VARDIR/debconf.db.old
	cp $VARDIR/templates.db $VARDIR/templates.db.old
	sed -e s/Debian::DebConf/Debconf/ \
		< $VARDIR/debconf.db.old > $VARDIR/debconf.db
	sed -e s/Debian::DebConf/Debconf/ \
		< $VARDIR/templates.db.old > $VARDIR/templates.db
	rm -f $VARDIR/debconf.db.old $VARDIR/templates.db.old
fi
