#!/bin/sh -e
#DEBHELPER#

# Hack up debconf database to use new object names. This goes away when we
# get a real database.
VARDIR=/var/lib/debconf
if [ -e $VARDIR/debconf.db -a -e $VARDIR/templates.db ] && \
   grep -q Debian::DebConf $VARDIR/debconf.db $VARDIR/templates.db; then
	cp $VARDIR/debconf.db $VARDIR/debconf.db.old
	cp $VARDIR/templates.db $VARDIR/templates.db.old
	sed -e s/Debian::DebConf/Debconf/ \
		< $VARDIR/debconf.db.old > $VARDIR/debconf.db
	sed -e s/Debian::DebConf/Debconf/ \
		< $VARDIR/templates.db.old > $VARDIR/templates.db
	rm -f $VARDIR/debconf.db.old $VARDIR/templates.db.old
fi
